# Generated by Django 4.1.4 on 2023-01-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
