# Generated by Django 4.1.4 on 2023-01-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_leads_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
